In [2]:
# ============================================================
# 00 — CONNECT GOOGLE DRIVE / PROJECT
# ============================================================

from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [9]:
# ============================================================
# PROJECT PATH
# ============================================================

from pathlib import Path
import sys

PROJECT_DIR = Path(
    "/content/drive/MyDrive/FitnessML_Master"
)

print(f"Project directory: {PROJECT_DIR}")
print(f"Exists: {PROJECT_DIR.exists()}")

Project directory: /content/drive/MyDrive/FitnessML_Master
Exists: True

In [10]:
# ============================================================
# ADD PROJECT TO PYTHON PATH
# ============================================================

if str(PROJECT_DIR) not in sys.path:
    sys.path.insert(0, str(PROJECT_DIR))

print("Project added to Python path.")

Project added to Python path.

In [14]:
# ============================================================
# 01 — FITBIT DATASET AUDIT
# ============================================================

from pathlib import Path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import config_fitbit as config

pd.set_option("display.max_columns", 100)
pd.set_option("display.width", 160)
pd.set_option("display.max_rows", 100)

print("config_fitbit loaded successfully")
print(f"Raw data directory: {config.RAW_DATA_DIR}")

print("=" * 70)
print("FITBIT DATASET AUDIT")
print("=" * 70)

print(f"Data directory: {config.RAW_DATA_DIR}")

config_fitbit loaded successfully
Raw data directory: /content/drive/MyDrive/FitnessML_Master/data/raw/fitbit
======================================================================
FITBIT DATASET AUDIT
======================================================================
Data directory: /content/drive/MyDrive/FitnessML_Master/data/raw/fitbit

In [15]:
# ============================================================
# DISCOVER RAW FILES
# ============================================================

RAW_DIR = Path(config.RAW_DATA_DIR)

csv_files = sorted(RAW_DIR.glob("*.csv"))

print(f"CSV files found: {len(csv_files)}")
print()

for path in csv_files:
    print(f"{path.name:45s} {path.stat().st_size / 1024**2:8.2f} MB")

CSV files found: 18

dailyActivity_merged.csv                          0.11 MB
dailyCalories_merged.csv                          0.02 MB
dailyIntensities_merged.csv                       0.07 MB
dailySteps_merged.csv                             0.02 MB
heartrate_seconds_merged.csv                     85.44 MB
hourlyCalories_merged.csv                         0.76 MB
hourlyIntensities_merged.csv                      0.86 MB
hourlySteps_merged.csv                            0.76 MB
minuteCaloriesNarrow_merged.csv                  63.37 MB
minuteCaloriesWide_merged.csv                    21.93 MB
minuteIntensitiesNarrow_merged.csv               44.21 MB
minuteIntensitiesWide_merged.csv                  3.16 MB
minuteMETsNarrow_merged.csv                      45.48 MB
minuteSleep_merged.csv                            8.44 MB
minuteStepsNarrow_merged.csv                     44.38 MB
minuteStepsWide_merged.csv                        3.32 MB
sleepDay_merged.csv                               0.02 MB
weightLogInfo_merged.csv                          0.01 MB

In [16]:
# ============================================================
# COLUMN DETECTION
# ============================================================

def find_column(columns, candidates):
    """
    Find first matching column from a list of candidates.
    Matching is case-insensitive.
    """

    normalized = {
        str(col).strip().lower(): col
        for col in columns
    }

    for candidate in candidates:
        candidate_norm = candidate.strip().lower()

        if candidate_norm in normalized:
            return normalized[candidate_norm]

    return None


def detect_structure(df):
    """
    Detect user/date/time columns without assuming
    identical schemas across Fitbit CSV files.
    """

    user_col = find_column(
        df.columns,
        ["Id", "user_id", "UserId", "userId"]
    )

    date_col = find_column(
        df.columns,
        [
            "Date",
            "ActivityDate",
            "SleepDay",
            "date",
            "datetime",
            "DateTime"
        ]
    )

    time_col = find_column(
        df.columns,
        [
            "Time",
            "time",
            "timestamp",
            "Timestamp"
        ]
    )

    return user_col, date_col, time_col

In [17]:
# ============================================================
# SINGLE FILE AUDIT
# ============================================================

def audit_file(path, chunksize=200_000):

    result = {
        "file": path.name,
        "size_mb": round(path.stat().st_size / 1024**2, 2),
        "rows": 0,
        "columns": 0,
        "users": np.nan,
        "date_min": pd.NaT,
        "date_max": pd.NaT,
        "duplicates": np.nan,
        "missing_cells": np.nan,
        "user_column": None,
        "date_column": None,
        "time_column": None,
    }

    # --------------------------------------------------------
    # Read header first
    # --------------------------------------------------------

    header = pd.read_csv(path, nrows=0)

    result["columns"] = len(header.columns)

    user_col, date_col, time_col = detect_structure(header)

    result["user_column"] = user_col
    result["date_column"] = date_col
    result["time_column"] = time_col

    # --------------------------------------------------------
    # Process file in chunks
    # --------------------------------------------------------

    unique_users = set()
    min_date = None
    max_date = None

    duplicate_count = 0
    missing_cells = 0

    for chunk in pd.read_csv(
        path,
        chunksize=chunksize,
        low_memory=False
    ):

        result["rows"] += len(chunk)

        missing_cells += int(chunk.isna().sum().sum())

        if user_col and user_col in chunk.columns:
            unique_users.update(
                chunk[user_col].dropna().unique()
            )

        if date_col and date_col in chunk.columns:

            dates = pd.to_datetime(
                chunk[date_col],
                errors="coerce"
            )

            if dates.notna().any():

                chunk_min = dates.min()
                chunk_max = dates.max()

                if min_date is None or chunk_min < min_date:
                    min_date = chunk_min

                if max_date is None or chunk_max > max_date:
                    max_date = chunk_max

        # Exact duplicate rows inside each chunk
        duplicate_count += int(chunk.duplicated().sum())

    result["users"] = len(unique_users) if user_col else np.nan
    result["date_min"] = min_date
    result["date_max"] = max_date
    result["duplicates"] = duplicate_count
    result["missing_cells"] = missing_cells

    return result

In [18]:
# ============================================================
# AUDIT ALL FILES
# ============================================================

audit_results = []

for i, path in enumerate(csv_files, start=1):

    print(
        f"[{i:02d}/{len(csv_files)}] "
        f"Auditing {path.name} ..."
    )

    try:
        result = audit_file(path)
        audit_results.append(result)

    except Exception as e:
        print(f"   ERROR: {e}")

        audit_results.append({
            "file": path.name,
            "size_mb": round(path.stat().st_size / 1024**2, 2),
            "rows": np.nan,
            "columns": np.nan,
            "users": np.nan,
            "date_min": pd.NaT,
            "date_max": pd.NaT,
            "duplicates": np.nan,
            "missing_cells": np.nan,
            "user_column": None,
            "date_column": None,
            "time_column": None,
        })

audit_df = pd.DataFrame(audit_results)

print()
print("=" * 70)
print("FILE AUDIT COMPLETE")
print("=" * 70)

display(audit_df)

[01/18] Auditing dailyActivity_merged.csv ...
[02/18] Auditing dailyCalories_merged.csv ...
[03/18] Auditing dailyIntensities_merged.csv ...
[04/18] Auditing dailySteps_merged.csv ...
[05/18] Auditing heartrate_seconds_merged.csv ...
[06/18] Auditing hourlyCalories_merged.csv ...
[07/18] Auditing hourlyIntensities_merged.csv ...
[08/18] Auditing hourlySteps_merged.csv ...
[09/18] Auditing minuteCaloriesNarrow_merged.csv ...
[10/18] Auditing minuteCaloriesWide_merged.csv ...
[11/18] Auditing minuteIntensitiesNarrow_merged.csv ...
[12/18] Auditing minuteIntensitiesWide_merged.csv ...
[13/18] Auditing minuteMETsNarrow_merged.csv ...
[14/18] Auditing minuteSleep_merged.csv ...
[15/18] Auditing minuteStepsNarrow_merged.csv ...
[16/18] Auditing minuteStepsWide_merged.csv ...
[17/18] Auditing sleepDay_merged.csv ...

/tmp/ipykernel_466/1079290415.py:64: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dates = pd.to_datetime(

[18/18] Auditing weightLogInfo_merged.csv ...

======================================================================
FILE AUDIT COMPLETE
======================================================================

/tmp/ipykernel_466/1079290415.py:64: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dates = pd.to_datetime(

,file,size_mb,rows,columns,users,date_min,date_max,duplicates,missing_cells,user_column,date_column,time_column
0,dailyActivity_merged.csv,0.11,940,15,33,2016-04-12 00:00:00,2016-05-12 00:00:00,0,0,Id,ActivityDate,None
1,dailyCalories_merged.csv,0.02,940,3,33,NaT,NaT,0,0,Id,None,None
2,dailyIntensities_merged.csv,0.07,940,10,33,NaT,NaT,0,0,Id,None,None
3,dailySteps_merged.csv,0.02,940,3,33,NaT,NaT,0,0,Id,None,None
4,heartrate_seconds_merged.csv,85.44,2483658,3,14,NaT,NaT,0,0,Id,None,Time
5,hourlyCalories_merged.csv,0.76,22099,3,33,NaT,NaT,0,0,Id,None,None
6,hourlyIntensities_merged.csv,0.86,22099,4,33,NaT,NaT,0,0,Id,None,None
7,hourlySteps_merged.csv,0.76,22099,3,33,NaT,NaT,0,0,Id,None,None
8,minuteCaloriesNarrow_merged.csv,63.37,1325580,3,33,NaT,NaT,0,0,Id,None,None
9,minuteCaloriesWide_merged.csv,21.93,21645,62,33,NaT,NaT,0,0,Id,None,None
10,minuteIntensitiesNarrow_merged.csv,44.21,1325580,3,33,NaT,NaT,0,0,Id,None,None
11,minuteIntensitiesWide_merged.csv,3.16,21645,62,33,NaT,NaT,0,0,Id,None,None
12,minuteMETsNarrow_merged.csv,45.48,1325580,3,33,NaT,NaT,0,0,Id,None,None
13,minuteSleep_merged.csv,8.44,188521,4,24,2016-04-11 20:48:00,2016-05-12 09:56:00,543,0,Id,date,None
14,minuteStepsNarrow_merged.csv,44.38,1325580,3,33,NaT,NaT,0,0,Id,None,None
15,minuteStepsWide_merged.csv,3.32,21645,62,33,NaT,NaT,0,0,Id,None,None
16,sleepDay_merged.csv,0.02,413,5,24,2016-04-12 00:00:00,2016-05-12 00:00:00,3,0,Id,SleepDay,None
17,weightLogInfo_merged.csv,0.01,67,8,8,2016-04-12 06:47:11,2016-05-12 23:59:59,0,65,Id,Date,None

In [19]:
# ============================================================
# USER COVERAGE ACROSS FILES
# ============================================================

file_users = {}

for path in csv_files:

    try:
        header = pd.read_csv(path, nrows=0)
        user_col, _, _ = detect_structure(header)

        if user_col is None:
            continue

        users = set()

        for chunk in pd.read_csv(
            path,
            usecols=[user_col],
            chunksize=200_000
        ):
            users.update(
                chunk[user_col].dropna().unique()
            )

        file_users[path.name] = users

    except Exception as e:
        print(f"{path.name}: {e}")

In [20]:
# ============================================================
# USER COVERAGE SUMMARY
# ============================================================

coverage = []

for filename, users in file_users.items():

    coverage.append({
        "file": filename,
        "users": len(users)
    })

coverage_df = (
    pd.DataFrame(coverage)
    .sort_values("users", ascending=False)
)

print("=" * 70)
print("USER COVERAGE")
print("=" * 70)

display(coverage_df)

======================================================================
USER COVERAGE
======================================================================

                                  file  users
0             dailyActivity_merged.csv     33
1             dailyCalories_merged.csv     33
2          dailyIntensities_merged.csv     33
3                dailySteps_merged.csv     33
5            hourlyCalories_merged.csv     33
6         hourlyIntensities_merged.csv     33
8      minuteCaloriesNarrow_merged.csv     33
7               hourlySteps_merged.csv     33
9        minuteCaloriesWide_merged.csv     33
10  minuteIntensitiesNarrow_merged.csv     33
15          minuteStepsWide_merged.csv     33
11    minuteIntensitiesWide_merged.csv     33
12         minuteMETsNarrow_merged.csv     33
14        minuteStepsNarrow_merged.csv     33
16                 sleepDay_merged.csv     24
13              minuteSleep_merged.csv     24
4         heartrate_seconds_merged.csv     14
17            weightLogInfo_merged.csv      8

In [21]:
# ============================================================
# USER OVERLAP
# ============================================================

core_files = [
    "dailyActivity_merged.csv",
    "heartRate_seconds_merged.csv",
    "sleepDay_merged.csv",
    "weightLogInfo_merged.csv"
]

available_core = [
    name for name in core_files
    if name in file_users
]

print("=" * 70)
print("USER OVERLAP — CORE FILES")
print("=" * 70)

for i in range(len(available_core)):

    for j in range(i + 1, len(available_core)):

        a = available_core[i]
        b = available_core[j]

        overlap = file_users[a] & file_users[b]

        print(
            f"{a:35s} × {b:35s} "
            f"→ {len(overlap)} common users"
        )

======================================================================
USER OVERLAP — CORE FILES
======================================================================
dailyActivity_merged.csv            × sleepDay_merged.csv                 → 24 common users
dailyActivity_merged.csv            × weightLogInfo_merged.csv            → 8 common users
sleepDay_merged.csv                 × weightLogInfo_merged.csv            → 6 common users

In [23]:
# ============================================================
# LOAD CORE TABLES
# ============================================================

daily_activity = pd.read_csv(
    RAW_DIR / "dailyActivity_merged.csv"
)

heart_rate = pd.read_csv(
    RAW_DIR / "heartrate_seconds_merged.csv"
)

sleep_day = pd.read_csv(
    RAW_DIR / "sleepDay_merged.csv"
)

weight_log = pd.read_csv(
    RAW_DIR / "weightLogInfo_merged.csv"
)

print("=" * 70)
print("CORE TABLES LOADED")
print("=" * 70)

print(f"daily_activity : {daily_activity.shape}")
print(f"heart_rate     : {heart_rate.shape}")
print(f"sleep_day      : {sleep_day.shape}")
print(f"weight_log     : {weight_log.shape}")

======================================================================
CORE TABLES LOADED
======================================================================
daily_activity : (940, 15)
heart_rate     : (2483658, 3)
sleep_day      : (413, 5)
weight_log     : (67, 8)

In [24]:
# ============================================================
# IMPORTANT:
# NO CROSS-TABLE MERGE IS PERFORMED IN THIS NOTEBOOK.
#
# Different Fitbit tables have different temporal granularities
# and different user/date coverage.
#
# A unified longitudinal dataset will be constructed only after
# the audit determines the appropriate temporal resolution,
# target variable and usable user/date intersection.
# ============================================================

print("=" * 70)
print("DATASET AUDIT COMPLETED")
print("=" * 70)

print("""
No cross-table merge was performed.

Next step:
1. Evaluate data quality and temporal coverage.
2. Determine the usable user/date intersection.
3. Select temporal granularity.
4. Define the target variable.
5. Construct the modeling dataset.
""")

======================================================================
DATASET AUDIT COMPLETED
======================================================================

No cross-table merge was performed.

Next step:
1. Evaluate data quality and temporal coverage.
2. Determine the usable user/date intersection.
3. Select temporal granularity.
4. Define the target variable.
5. Construct the modeling dataset.

FILE: dailyActivity
------------------------------------------------
columns
dtypes
missing %
unique users
date column
date range
duplicate rows

In [26]:
# ============================================================
# CORE FILE SCHEMA
# ============================================================

core_paths = {
    "daily_activity": RAW_DIR / "dailyActivity_merged.csv",
    "heart_rate": RAW_DIR / "heartrate_seconds_merged.csv",
    "sleep_day": RAW_DIR / "sleepDay_merged.csv",
    "weight_log": RAW_DIR / "weightLogInfo_merged.csv",
}

for name, path in core_paths.items():

    print("\n" + "=" * 70)
    print(name.upper())
    print("=" * 70)

    df_sample = pd.read_csv(path, nrows=5)

    print("\nColumns:")
    for col in df_sample.columns:
        print(f"  {col}")

    print("\nDtypes:")
    print(df_sample.dtypes)

======================================================================
DAILY_ACTIVITY
======================================================================

Columns:
  Id
  ActivityDate
  TotalSteps
  TotalDistance
  TrackerDistance
  LoggedActivitiesDistance
  VeryActiveDistance
  ModeratelyActiveDistance
  LightActiveDistance
  SedentaryActiveDistance
  VeryActiveMinutes
  FairlyActiveMinutes
  LightlyActiveMinutes
  SedentaryMinutes
  Calories

Dtypes:
Id                            int64
ActivityDate                 object
TotalSteps                    int64
TotalDistance               float64
TrackerDistance             float64
LoggedActivitiesDistance      int64
VeryActiveDistance          float64
ModeratelyActiveDistance    float64
LightActiveDistance         float64
SedentaryActiveDistance       int64
VeryActiveMinutes             int64
FairlyActiveMinutes           int64
LightlyActiveMinutes          int64
SedentaryMinutes              int64
Calories                      int64
dtype: object

======================================================================
HEART_RATE
======================================================================

Columns:
  Id
  Time
  Value

Dtypes:
Id        int64
Time     object
Value     int64
dtype: object

======================================================================
SLEEP_DAY
======================================================================

Columns:
  Id
  SleepDay
  TotalSleepRecords
  TotalMinutesAsleep
  TotalTimeInBed

Dtypes:
Id                     int64
SleepDay              object
TotalSleepRecords      int64
TotalMinutesAsleep     int64
TotalTimeInBed         int64
dtype: object

======================================================================
WEIGHT_LOG
======================================================================

Columns:
  Id
  Date
  WeightKg
  WeightPounds
  Fat
  BMI
  IsManualReport
  LogId

Dtypes:
Id                  int64
Date               object
WeightKg          float64
WeightPounds      float64
Fat               float64
BMI               float64
IsManualReport       bool
LogId               int64
dtype: object

In [28]:
# ============================================================
# MISSING VALUES — CORE FILES
# ============================================================

for name, path in core_paths.items():

    print("\n" + "=" * 70)
    print(f"MISSING VALUES: {name.upper()}")
    print("=" * 70)

    df = pd.read_csv(path)

    missing = pd.DataFrame({
        "missing": df.isna().sum(),
        "missing_%": df.isna().mean() * 100
    })

    display(
        missing[missing["missing"] > 0]
        .sort_values("missing", ascending=False)
    )

======================================================================
MISSING VALUES: DAILY_ACTIVITY
======================================================================

Empty DataFrame
Columns: [missing, missing_%]
Index: []

======================================================================
MISSING VALUES: HEART_RATE
======================================================================

Empty DataFrame
Columns: [missing, missing_%]
Index: []

======================================================================
MISSING VALUES: SLEEP_DAY
======================================================================

Empty DataFrame
Columns: [missing, missing_%]
Index: []

======================================================================
MISSING VALUES: WEIGHT_LOG
======================================================================

     missing  missing_%
Fat       65  97.014925

In [29]:
# ============================================================
# WEIGHT LOG INSPECTION
# ============================================================

print("=" * 70)
print("WEIGHT LOG SAMPLE")
print("=" * 70)

display(
    weight_log[
        [
            "Id",
            "Date",
            "WeightKg",
            "WeightPounds",
            "BMI",
            "IsManualReport"
        ]
    ].sort_values(["Id", "Date"])
)

======================================================================
WEIGHT LOG SAMPLE
======================================================================

            Id                   Date    WeightKg  WeightPounds        BMI  IsManualReport
0   1503960366   5/2/2016 11:59:59 PM   52.599998    115.963147  22.650000            True
1   1503960366   5/3/2016 11:59:59 PM   52.599998    115.963147  22.650000            True
2   1927972279   4/13/2016 1:08:52 AM  133.500000    294.317120  47.540001           False
3   2873212765  4/21/2016 11:59:59 PM   56.700001    125.002104  21.450001            True
4   2873212765  5/12/2016 11:59:59 PM   57.299999    126.324875  21.690001            True
5   4319703577  4/17/2016 11:59:59 PM   72.400002    159.614681  27.450001            True
6   4319703577   5/4/2016 11:59:59 PM   72.300003    159.394222  27.379999            True
7   4558609924  4/18/2016 11:59:59 PM   69.699997    153.662190  27.250000            True
8   4558609924  4/25/2016 11:59:59 PM   70.300003    154.984977  27.459999            True
9   4558609924   5/1/2016 11:59:59 PM   69.900002    154.103125  27.320000            True
10  4558609924   5/2/2016 11:59:59 PM   69.199997    152.559879  27.040001            True
11  4558609924   5/9/2016 11:59:59 PM   69.099998    152.339420  27.000000            True
12  5577150313   4/17/2016 9:17:55 AM   90.699997    199.959265  28.000000           False
13  6962181067  4/12/2016 11:59:59 PM   62.500000    137.788914  24.389999            True
14  6962181067  4/13/2016 11:59:59 PM   62.099998    136.907061  24.240000            True
15  6962181067  4/14/2016 11:59:59 PM   61.700001    136.025217  24.100000            True
16  6962181067  4/15/2016 11:59:59 PM   61.500000    135.584291  24.000000            True
17  6962181067  4/16/2016 11:59:59 PM   62.000000    136.686603  24.209999            True
18  6962181067  4/17/2016 11:59:59 PM   61.400002    135.363832  23.959999            True
19  6962181067  4/18/2016 11:59:59 PM   61.200001    134.922906  23.889999            True
20  6962181067  4/19/2016 11:59:59 PM   61.400002    135.363832  23.959999            True
21  6962181067  4/20/2016 11:59:59 PM   61.700001    136.025217  24.100000            True
22  6962181067  4/21/2016 11:59:59 PM   61.400002    135.363832  23.959999            True
23  6962181067  4/22/2016 11:59:59 PM   61.400002    135.363832  23.959999            True
24  6962181067  4/23/2016 11:59:59 PM   61.500000    135.584291  24.000000            True
25  6962181067  4/24/2016 11:59:59 PM   61.500000    135.584291  24.000000            True
26  6962181067  4/25/2016 11:59:59 PM   61.700001    136.025217  24.100000            True
27  6962181067  4/27/2016 11:59:59 PM   61.200001    134.922906  23.889999            True
28  6962181067  4/28/2016 11:59:59 PM   61.200001    134.922906  23.889999            True
29  6962181067  4/29/2016 11:59:59 PM   61.400002    135.363832  23.959999            True
30  6962181067  4/30/2016 11:59:59 PM   61.000000    134.481980  23.820000            True
31  6962181067   5/1/2016 11:59:59 PM   61.700001    136.025217  24.100000            True
40  6962181067  5/10/2016 11:59:59 PM   62.099998    136.907061  24.240000            True
41  6962181067  5/11/2016 11:59:59 PM   61.900002    136.466144  24.170000            True
42  6962181067  5/12/2016 11:59:59 PM   61.900002    136.466144  24.170000            True
32  6962181067   5/2/2016 11:59:59 PM   61.500000    135.584291  24.000000            True
33  6962181067   5/3/2016 11:59:59 PM   61.000000    134.481980  23.820000            True
34  6962181067   5/4/2016 11:59:59 PM   61.099998    134.702439  23.850000            True
35  6962181067   5/5/2016 11:59:59 PM   61.299999    135.143365  23.930000            True
36  6962181067   5/6/2016 11:59:59 PM   61.500000    135.584291  24.000000            True
37  6962181067   5/7/2016 11:59:59 PM   61.200001    134.922906  23.889999            True
38  6962181067   5/8/2016 11:59:59 PM   61.200001    134.922906  23.889999            True
39  6962181067   5/9/2016 11:59:59 PM   62.400002    137.568455  24.350000            True
43  8877689391   4/12/2016 6:47:11 AM   85.800003    189.156628  25.680000           False
44  8877689391   4/13/2016 6:55:00 AM   84.900002    187.172464  25.410000           False
45  8877689391   4/14/2016 6:48:43 AM   84.500000    186.290612  25.309999           False
46  8877689391   4/16/2016 1:39:25 PM   85.500000    188.495234  25.590000           False
47  8877689391   4/18/2016 6:51:14 AM   85.800003    189.156628  25.680000           False
48  8877689391   4/19/2016 6:39:31 AM   85.300003    188.054316  25.530001           False
49  8877689391   4/20/2016 6:44:54 AM   84.900002    187.172464  25.410000           False
50  8877689391   4/21/2016 6:50:27 AM   84.500000    186.290612  25.290001           False
51  8877689391   4/23/2016 7:22:28 AM   85.500000    188.495234  25.590000           False
52  8877689391   4/24/2016 7:38:05 AM   85.500000    188.495234  25.590000           False
53  8877689391   4/25/2016 6:40:16 AM   85.400002    188.274775  25.559999           False
54  8877689391   4/26/2016 6:50:27 AM   85.099998    187.613382  25.490000           False
55  8877689391   4/27/2016 6:51:05 AM   85.400002    188.274775  25.559999           False
56  8877689391   4/28/2016 6:50:03 AM   85.099998    187.613382  25.490000           False
57  8877689391   4/29/2016 6:49:55 AM   84.900002    187.172464  25.410000           False
58  8877689391   4/30/2016 7:49:03 AM   85.500000    188.495234  25.590000           False
59  8877689391    5/1/2016 8:47:49 AM   85.300003    188.054316  25.530001           False
65  8877689391   5/11/2016 6:51:47 AM   85.400002    188.274775  25.559999           False
66  8877689391   5/12/2016 6:42:53 AM   84.000000    185.188300  25.139999           False
60  8877689391    5/3/2016 6:49:41 AM   84.900002    187.172464  25.410000           False
61  8877689391    5/4/2016 6:48:22 AM   84.400002    186.070153  25.260000           False
62  8877689391    5/6/2016 6:43:35 AM   85.000000    187.392923  25.440001           False
63  8877689391    5/8/2016 7:35:53 AM   85.400002    188.274775  25.559999           False
64  8877689391    5/9/2016 6:39:44 AM   85.500000    188.495234  25.610001           False

In [30]:
# ============================================================
# WEIGHT RECORDS PER USER
# ============================================================

weight_records = (
    weight_log
    .groupby("Id")
    .agg(
        records=("Id", "size"),
        first_date=("Date", "min"),
        last_date=("Date", "max"),
        weight_min=("WeightKg", "min"),
        weight_max=("WeightKg", "max"),
        weight_mean=("WeightKg", "mean"),
    )
    .reset_index()
)

display(weight_records)

           Id  records             first_date              last_date  weight_min  weight_max  weight_mean
0  1503960366        2   5/2/2016 11:59:59 PM   5/3/2016 11:59:59 PM   52.599998   52.599998    52.599998
1  1927972279        1   4/13/2016 1:08:52 AM   4/13/2016 1:08:52 AM  133.500000  133.500000   133.500000
2  2873212765        2  4/21/2016 11:59:59 PM  5/12/2016 11:59:59 PM   56.700001   57.299999    57.000000
3  4319703577        2  4/17/2016 11:59:59 PM   5/4/2016 11:59:59 PM   72.300003   72.400002    72.350002
4  4558609924        5  4/18/2016 11:59:59 PM   5/9/2016 11:59:59 PM   69.099998   70.300003    69.639999
5  5577150313        1   4/17/2016 9:17:55 AM   4/17/2016 9:17:55 AM   90.699997   90.699997    90.699997
6  6962181067       30  4/12/2016 11:59:59 PM   5/9/2016 11:59:59 PM   61.000000   62.500000    61.553334
7  8877689391       24   4/12/2016 6:47:11 AM    5/9/2016 6:39:44 AM   84.000000   85.800003    85.145834

In [31]:
# ============================================================
# TEMPORAL COVERAGE — DAILY ACTIVITY
# ============================================================

daily_activity["ActivityDate"] = pd.to_datetime(
    daily_activity["ActivityDate"]
)

user_temporal = (
    daily_activity
    .groupby("Id")
    .agg(
        records=("Id", "size"),
        first_date=("ActivityDate", "min"),
        last_date=("ActivityDate", "max"),
        unique_days=("ActivityDate", "nunique"),
    )
    .reset_index()
)

user_temporal["calendar_span"] = (
    user_temporal["last_date"]
    - user_temporal["first_date"]
).dt.days + 1

user_temporal["coverage_pct"] = (
    user_temporal["unique_days"]
    / user_temporal["calendar_span"]
    * 100
)

display(
    user_temporal
    .sort_values("unique_days", ascending=False)
)

            Id  records first_date  last_date  unique_days  calendar_span  coverage_pct
0   1503960366       31 2016-04-12 2016-05-12           31             31         100.0
1   1624580081       31 2016-04-12 2016-05-12           31             31         100.0
3   1844505072       31 2016-04-12 2016-05-12           31             31         100.0
4   1927972279       31 2016-04-12 2016-05-12           31             31         100.0
5   2022484408       31 2016-04-12 2016-05-12           31             31         100.0
7   2320127002       31 2016-04-12 2016-05-12           31             31         100.0
6   2026352035       31 2016-04-12 2016-05-12           31             31         100.0
12  4020332650       31 2016-04-12 2016-05-12           31             31         100.0
9   2873212765       31 2016-04-12 2016-05-12           31             31         100.0
16  4445114986       31 2016-04-12 2016-05-12           31             31         100.0
14  4319703577       31 2016-04-12 2016-05-12           31             31         100.0
15  4388161847       31 2016-04-12 2016-05-12           31             31         100.0
29  8378563200       31 2016-04-12 2016-05-12           31             31         100.0
24  6962181067       31 2016-04-12 2016-05-12           31             31         100.0
19  5553957443       31 2016-04-12 2016-05-12           31             31         100.0
18  4702921684       31 2016-04-12 2016-05-12           31             31         100.0
17  4558609924       31 2016-04-12 2016-05-12           31             31         100.0
32  8877689391       31 2016-04-12 2016-05-12           31             31         100.0
30  8583815059       31 2016-04-12 2016-05-12           31             31         100.0
27  8053475328       31 2016-04-12 2016-05-12           31             31         100.0
26  7086361926       31 2016-04-12 2016-05-12           31             31         100.0
2   1644430081       30 2016-04-12 2016-05-11           30             30         100.0
20  5577150313       30 2016-04-12 2016-05-11           30             30         100.0
11  3977333714       30 2016-04-12 2016-05-11           30             30         100.0
22  6290855005       29 2016-04-12 2016-05-10           29             29         100.0
31  8792009665       29 2016-04-12 2016-05-10           29             29         100.0
21  6117666160       28 2016-04-12 2016-05-09           28             28         100.0
25  7007744171       26 2016-04-12 2016-05-07           26             26         100.0
23  6775888955       26 2016-04-12 2016-05-07           26             26         100.0
10  3372868164       20 2016-04-12 2016-05-01           20             20         100.0
28  8253242879       19 2016-04-12 2016-04-30           19             19         100.0
8   2347167796       18 2016-04-12 2016-04-29           18             18         100.0
13  4057192912        4 2016-04-12 2016-04-15            4              4         100.0

In [32]:
# ============================================================
# MISSING DAYS INSIDE USER TIMELINES
# ============================================================

user_temporal["missing_days"] = (
    user_temporal["calendar_span"]
    - user_temporal["unique_days"]
)

display(
    user_temporal[
        [
            "Id",
            "unique_days",
            "calendar_span",
            "missing_days",
            "coverage_pct"
        ]
    ]
    .sort_values("coverage_pct")
)

            Id  unique_days  calendar_span  missing_days  coverage_pct
0   1503960366           31             31             0         100.0
1   1624580081           31             31             0         100.0
2   1644430081           30             30             0         100.0
3   1844505072           31             31             0         100.0
4   1927972279           31             31             0         100.0
5   2022484408           31             31             0         100.0
6   2026352035           31             31             0         100.0
7   2320127002           31             31             0         100.0
8   2347167796           18             18             0         100.0
9   2873212765           31             31             0         100.0
10  3372868164           20             20             0         100.0
11  3977333714           30             30             0         100.0
12  4020332650           31             31             0         100.0
13  4057192912            4              4             0         100.0
14  4319703577           31             31             0         100.0
15  4388161847           31             31             0         100.0
16  4445114986           31             31             0         100.0
17  4558609924           31             31             0         100.0
18  4702921684           31             31             0         100.0
19  5553957443           31             31             0         100.0
20  5577150313           30             30             0         100.0
21  6117666160           28             28             0         100.0
22  6290855005           29             29             0         100.0
23  6775888955           26             26             0         100.0
24  6962181067           31             31             0         100.0
25  7007744171           26             26             0         100.0
26  7086361926           31             31             0         100.0
27  8053475328           31             31             0         100.0
28  8253242879           19             19             0         100.0
29  8378563200           31             31             0         100.0
30  8583815059           31             31             0         100.0
31  8792009665           29             29             0         100.0
32  8877689391           31             31             0         100.0