In [5]:
# ============================================================
# 009 — FINAL RESULTS
# ============================================================
from pathlib import Path
import json
import pandas as pd
import numpy as np

from google.colab import drive
drive.mount("/content/drive")

print("=" * 70)
print("009 — FINAL RESULTS")
print("=" * 70)

PROJECT_ROOT = Path("/content/drive/MyDrive/FitnessML_Master")
TABLES_DIR = PROJECT_ROOT / "tables"
RESULTS_DIR = PROJECT_ROOT / "results"
OUTPUT_DIR = RESULTS_DIR / "009_final_results"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


def load_table(filename, required=True):
    path = TABLES_DIR / filename
    if not path.exists():
        if required:
            raise FileNotFoundError(f"Required table not found: {path}")
        return None
    return pd.read_csv(path)


def require_columns(df, columns, name):
    missing = set(columns) - set(df.columns)
    if missing:
        raise ValueError(
            f"{name}: missing columns {sorted(missing)}"
        )

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
======================================================================
009 — FINAL RESULTS
======================================================================

In [9]:
# ============================================================
# LOAD 005–007 RESULTS
# ============================================================

def load_table(filename):
    path = TABLES_DIR / filename

    if not path.exists():
        raise FileNotFoundError(
            f"Required table not found:\n{path}"
        )

    return pd.read_csv(path)

In [10]:
# ------------------------------------------------------------
# 005
# ------------------------------------------------------------

baseline_results = load_table(
    "005_baseline_results.csv"
)

ml_results = load_table(
    "005_ml_results.csv"
)

In [11]:
# ------------------------------------------------------------
# 005
# ------------------------------------------------------------

baseline_results = load_table(
    "005_baseline_results.csv"
)

ml_results = load_table(
    "005_ml_results.csv"
)

In [14]:
# ------------------------------------------------------------
# 007
# ------------------------------------------------------------
ablation_results = load_table(
    "007_ablation_results.csv"
)

calories_history_ablation = load_table(
    "007_calories_history_ablation.csv"
)

importance_comparison = load_table(
    "007_importance_comparison.csv"
)

permutation_importance = load_table(
    "007_permutation_importance.csv"
)

rf_feature_importance = load_table(
    "007_rf_feature_importance.csv"
)
print("=" * 70)
print("005–007 RESULTS LOADED")
print("=" * 70)

print(f"005 baseline:       {baseline_results.shape}")
print(f"005 ML:             {ml_results.shape}")
print(f"006 validation:     {validation_results.shape}")
print(f"006 summary:        {validation_summary.shape}")
print(f"007 ablation:       {ablation_results.shape}")
print(f"007 history:        {calories_history_ablation.shape}")
print(f"007 importance:     {importance_comparison.shape}")
print(f"007 permutation:    {permutation_importance.shape}")
print(f"007 RF importance:  {rf_feature_importance.shape}")

======================================================================
005–007 RESULTS LOADED
======================================================================
005 baseline:       (4, 4)
005 ML:             (13, 4)
006 validation:     (15, 5)
006 summary:        (5, 7)
007 ablation:       (2, 5)
007 history:        (2, 5)
007 importance:     (65, 7)
007 permutation:    (65, 3)
007 RF importance:  (65, 2)

In [15]:
# ============================================================
# 005 — SINGLE SPLIT RESULTS
# ============================================================

print("\n" + "=" * 70)
print("005 — SINGLE SPLIT RESULTS")
print("=" * 70)

single_split = (
    ml_results
    .sort_values("R2", ascending=False)
    .reset_index(drop=True)
)

display(
    single_split.round(4)
)

======================================================================
005 — SINGLE SPLIT RESULTS
======================================================================

                               Model       MAE      RMSE      R2
0               Decision Tree — Base  496.2134  719.3816  0.2924
1           Linear Regression — Base  496.0381  738.5981  0.2541
2       Random Forest — All Features  481.7334  740.4334  0.2504
3                          User Mean  486.7907  753.1806  0.2244
4   Linear Regression — All Features  485.0494  754.3263  0.2220
5                         7-Day Mean  479.9669  757.9682  0.2145
6        Linear Regression — Rolling  492.4569  758.8200  0.2127
7            Linear Regression — Lag  503.1245  760.2357  0.2098
8                Decision Tree — Lag  566.1334  784.0076  0.1596
9            Decision Tree — Rolling  517.9900  787.8379  0.1513
10      Decision Tree — All Features  533.4941  789.1613  0.1485
11                      Previous Day  542.4320  803.8786  0.1164
12                       Global Mean  732.1124  898.7329 -0.1044

In [20]:
# ============================================================
# FINAL MODEL COMPARISON
# ============================================================

print("\n" + "=" * 70)
print("FINAL MODEL COMPARISON")
print("=" * 70)

final_model_comparison = (
    walk_forward[
        [
            "Model",
            "MAE",
            "MAE_std",
            "RMSE",
            "RMSE_std",
            "R2",
            "R2_std",
            "Evaluation"
        ]
    ]
    .copy()
)

display(
    final_model_comparison.round(4)
)

======================================================================
FINAL MODEL COMPARISON
======================================================================

,Model,MAE,MAE_std,RMSE,RMSE_std,R2,R2_std,Evaluation
0,Random Forest — All Features,373.7911,94.3970,563.8099,154.0266,0.4381,0.1637,Walk-forward validation
1,7-Day Mean,366.4455,98.6326,566.3899,166.4228,0.4325,0.1890,Walk-forward validation
2,User Mean,367.9359,102.9410,572.8226,156.4973,0.4199,0.1693,Walk-forward validation
3,Linear Regression — Base,389.7171,92.3465,576.5766,141.1027,0.4124,0.1377,Walk-forward validation
4,Decision Tree — Base,404.6027,81.0518,582.5245,121.5451,0.3992,0.1001,Walk-forward validation

In [22]:
# ============================================================
# TABLE STRUCTURE OVERVIEW
# ============================================================

print("\n" + "=" * 70)
print("TABLE STRUCTURE OVERVIEW")
print("=" * 70)

loaded_tables = {
    "005_baseline_results": baseline_results,
    "005_ml_results": ml_results,
    "006_validation_results": validation_results,
    "006_validation_summary": validation_summary,
    "007_ablation_results": ablation_results,
    "007_calories_history_ablation": calories_history_ablation,
    "007_importance_comparison": importance_comparison,
    "007_permutation_importance": permutation_importance,
    "007_rf_feature_importance": rf_feature_importance,
}

for name, df in loaded_tables.items():

    print("\n" + "-" * 70)
    print(name)
    print("-" * 70)

    print("Columns:")
    print(", ".join(df.columns.astype(str)))

    print(f"Shape: {df.shape}")

======================================================================
TABLE STRUCTURE OVERVIEW
======================================================================

----------------------------------------------------------------------
005_baseline_results
----------------------------------------------------------------------
Columns:
Model, MAE, RMSE, R2
Shape: (4, 4)

----------------------------------------------------------------------
005_ml_results
----------------------------------------------------------------------
Columns:
Model, MAE, RMSE, R2
Shape: (13, 4)

----------------------------------------------------------------------
006_validation_results
----------------------------------------------------------------------
Columns:
fold, model, MAE, RMSE, R2
Shape: (15, 5)

----------------------------------------------------------------------
006_validation_summary
----------------------------------------------------------------------
Columns:
model, MAE_mean, MAE_std, RMSE_mean, RMSE_std, R2_mean, R2_std
Shape: (5, 7)

----------------------------------------------------------------------
007_ablation_results
----------------------------------------------------------------------
Columns:
Model, Removed Feature, MAE, RMSE, R2
Shape: (2, 5)

----------------------------------------------------------------------
007_calories_history_ablation
----------------------------------------------------------------------
Columns:
Model, Features, MAE, RMSE, R2
Shape: (2, 5)

----------------------------------------------------------------------
007_importance_comparison
----------------------------------------------------------------------
Columns:
feature, importance, importance_mean, importance_std, rank_builtin, rank_permutation, group
Shape: (65, 7)

----------------------------------------------------------------------
007_permutation_importance
----------------------------------------------------------------------
Columns:
feature, importance_mean, importance_std
Shape: (65, 3)

----------------------------------------------------------------------
007_rf_feature_importance
----------------------------------------------------------------------
Columns:
feature, importance
Shape: (65, 2)

In [23]:
# ============================================================
# 009 — CORE RESULTS CONSOLIDATION
# ============================================================

print("=" * 70)
print("CORE RESULTS CONSOLIDATION")
print("=" * 70)

======================================================================
CORE RESULTS CONSOLIDATION
======================================================================

In [25]:
# ============================================================
# 005 — BASELINE RESULTS
# ============================================================

print("\n" + "=" * 70)
print("005 — BASELINE RESULTS")
print("=" * 70)

display(
    baseline_results
    .sort_values("R2", ascending=False)
    .round(4)
)


print("\n" + "=" * 70)
print("005 — ML RESULTS")
print("=" * 70)

display(
    ml_results
    .sort_values("R2", ascending=False)
    .round(4)
)

======================================================================
005 — BASELINE RESULTS
======================================================================

          Model       MAE      RMSE      R2
1     User Mean  486.7907  753.1806  0.2244
3    7-Day Mean  479.9669  757.9682  0.2145
2  Previous Day  542.4320  803.8786  0.1164
0   Global Mean  732.1124  898.7329 -0.1044

======================================================================
005 — ML RESULTS
======================================================================

                               Model       MAE      RMSE      R2
5               Decision Tree — Base  496.2134  719.3816  0.2924
4           Linear Regression — Base  496.0381  738.5981  0.2541
12      Random Forest — All Features  481.7334  740.4334  0.2504
1                          User Mean  486.7907  753.1806  0.2244
10  Linear Regression — All Features  485.0494  754.3263  0.2220
3                         7-Day Mean  479.9669  757.9682  0.2145
8        Linear Regression — Rolling  492.4569  758.8200  0.2127
6            Linear Regression — Lag  503.1245  760.2357  0.2098
7                Decision Tree — Lag  566.1334  784.0076  0.1596
9            Decision Tree — Rolling  517.9900  787.8379  0.1513
11      Decision Tree — All Features  533.4941  789.1613  0.1485
2                       Previous Day  542.4320  803.8786  0.1164
0                        Global Mean  732.1124  898.7329 -0.1044

In [31]:
# ------------------------------------------------------------
# 006 — WALK-FORWARD VALIDATION
# ------------------------------------------------------------

validation_summary = (
    validation_summary
    .sort_values("R2_mean", ascending=False)
    .reset_index(drop=True)
)


print("\n" + "=" * 70)
print("006 — WALK-FORWARD VALIDATION SUMMARY")
print("=" * 70)

display(
    validation_summary.round(4)
)

======================================================================
006 — WALK-FORWARD VALIDATION SUMMARY
======================================================================

,model,MAE_mean,MAE_std,RMSE_mean,RMSE_std,R2_mean,R2_std
0,Random Forest — All Features,373.7911,94.3970,563.8099,154.0266,0.4381,0.1637
1,7-Day Mean,366.4455,98.6326,566.3899,166.4228,0.4325,0.1890
2,User Mean,367.9359,102.9410,572.8226,156.4973,0.4199,0.1693
3,Linear Regression — Base,389.7171,92.3465,576.5766,141.1027,0.4124,0.1377
4,Decision Tree — Base,404.6027,81.0518,582.5245,121.5451,0.3992,0.1001

In [32]:
# ------------------------------------------------------------
# 007 — ABLATION
# ------------------------------------------------------------

calories_ablation = calories_history_ablation


print("\n" + "=" * 70)
print("007 — ABLATION RESULTS")
print("=" * 70)

display(
    ablation_results.round(4)
)


print("\n" + "=" * 70)
print("007 — CALORIES HISTORY ABLATION")
print("=" * 70)

display(
    calories_ablation.round(4)
)

======================================================================
007 — ABLATION RESULTS
======================================================================

,Model,Removed Feature,MAE,RMSE,R2
0,Random Forest — All Features,NaN,481.7334,740.4334,0.2504
1,Random Forest — Ablation,Calories_rolling_mean_7,484.4384,738.2580,0.2548

======================================================================
007 — CALORIES HISTORY ABLATION
======================================================================

                           Model  Features       MAE      RMSE      R2
0   Random Forest — All Features        65  481.7334  740.4334  0.2504
1  Random Forest — Activity Only        56  566.6922  763.6063  0.2027

In [33]:
# ============================================================
# 009 — LOCATE 008 RESULTS
# ============================================================

print("=" * 70)
print("SEARCHING FOR 008 RESULTS")
print("=" * 70)

for path in PROJECT_ROOT.rglob("*008*"):
    if path.is_file():
        print(path)

======================================================================
SEARCHING FOR 008 RESULTS
======================================================================
/content/drive/MyDrive/FitnessML_Master/notebooks/Fitbit/008_interpretability.ipynb
/content/drive/MyDrive/FitnessML_Master/.git/objects/33/a274776fde3c2f00080643a89ea5fafc29f65d

In [34]:
# ============================================================
# 009 — FINAL MODEL COMPARISON
# ============================================================

print("=" * 70)
print("FINAL MODEL COMPARISON")
print("=" * 70)

======================================================================
FINAL MODEL COMPARISON
======================================================================

In [35]:
# ------------------------------------------------------------
# SINGLE-SPLIT RESULTS
# ------------------------------------------------------------

single_split = ml_results.copy()

single_split["Evaluation"] = "Single train/test split"

In [36]:
# ------------------------------------------------------------
# WALK-FORWARD RESULTS
# ------------------------------------------------------------

walk_forward = validation_summary[
    ["model", "MAE_mean", "RMSE_mean", "R2_mean"]
].copy()

walk_forward = walk_forward.rename(columns={
    "model": "Model",
    "MAE_mean": "MAE",
    "RMSE_mean": "RMSE",
    "R2_mean": "R2"
})

walk_forward["Evaluation"] = "Walk-forward validation"

single_split_final = single_split[
    ["Model", "MAE", "RMSE", "R2", "Evaluation"]
].copy()

In [37]:
# ------------------------------------------------------------
# COMBINED TABLE
# ------------------------------------------------------------

final_comparison = pd.concat(
    [
        single_split_final,
        walk_forward[
            ["Model", "MAE", "RMSE", "R2", "Evaluation"]
        ]
    ],
    ignore_index=True
)

display(
    final_comparison
    .sort_values(
        ["Evaluation", "R2"],
        ascending=[True, False]
    )
    .round(4)
)

,Model,MAE,RMSE,R2,Evaluation
5,Decision Tree — Base,496.2134,719.3816,0.2924,Single train/test split
4,Linear Regression — Base,496.0381,738.5981,0.2541,Single train/test split
12,Random Forest — All Features,481.7334,740.4334,0.2504,Single train/test split
1,User Mean,486.7907,753.1806,0.2244,Single train/test split
10,Linear Regression — All Features,485.0494,754.3263,0.2220,Single train/test split
3,7-Day Mean,479.9669,757.9682,0.2145,Single train/test split
8,Linear Regression — Rolling,492.4569,758.8200,0.2127,Single train/test split
6,Linear Regression — Lag,503.1245,760.2357,0.2098,Single train/test split
7,Decision Tree — Lag,566.1334,784.0076,0.1596,Single train/test split
9,Decision Tree — Rolling,517.9900,787.8379,0.1513,Single train/test split
11,Decision Tree — All Features,533.4941,789.1613,0.1485,Single train/test split
2,Previous Day,542.4320,803.8786,0.1164,Single train/test split
0,Global Mean,732.1124,898.7329,-0.1044,Single train/test split
13,Random Forest — All Features,373.7911,563.8099,0.4381,Walk-forward validation
14,7-Day Mean,366.4455,566.3899,0.4325,Walk-forward validation
15,User Mean,367.9359,572.8226,0.4199,Walk-forward validation
16,Linear Regression — Base,389.7171,576.5766,0.4124,Walk-forward validation
17,Decision Tree — Base,404.6027,582.5245,0.3992,Walk-forward validation

In [38]:
# ============================================================
# 009 — FINAL CANDIDATE MODELS
# ============================================================

print("=" * 70)
print("FINAL CANDIDATE MODELS")
print("=" * 70)

candidate_names = [
    "Random Forest — All Features",
    "7-Day Mean",
    "User Mean",
    "Linear Regression — Base",
    "Decision Tree — Base"
]

candidate_summary = validation_summary[
    validation_summary["model"].isin(candidate_names)
].copy()

candidate_summary = candidate_summary.sort_values(
    "R2_mean",
    ascending=False
)

display(
    candidate_summary.round(4)
)

======================================================================
FINAL CANDIDATE MODELS
======================================================================

,model,MAE_mean,MAE_std,RMSE_mean,RMSE_std,R2_mean,R2_std
0,Random Forest — All Features,373.7911,94.3970,563.8099,154.0266,0.4381,0.1637
1,7-Day Mean,366.4455,98.6326,566.3899,166.4228,0.4325,0.1890
2,User Mean,367.9359,102.9410,572.8226,156.4973,0.4199,0.1693
3,Linear Regression — Base,389.7171,92.3465,576.5766,141.1027,0.4124,0.1377
4,Decision Tree — Base,404.6027,81.0518,582.5245,121.5451,0.3992,0.1001

In [41]:
# ============================================================
# SAVE FINAL MODEL COMPARISON TABLES
# ============================================================

print("\n" + "=" * 70)
print("SAVING FINAL COMPARISON TABLES")
print("=" * 70)

# Use the existing project results directory
FINAL_DIR = RESULTS_DIR / "009_final_results"
FINAL_DIR.mkdir(parents=True, exist_ok=True)


# ------------------------------------------------------------
# 1. Complete model comparison
# ------------------------------------------------------------

final_model_comparison.to_csv(
    FINAL_DIR / "final_model_comparison.csv",
    index=False
)

print("✓ final_model_comparison.csv")


# ------------------------------------------------------------
# 2. Final candidate models
#    = 006 walk-forward validation summary
# ------------------------------------------------------------

final_candidate_models = (
    validation_summary
    .copy()
    .sort_values("R2_mean", ascending=False)
    .reset_index(drop=True)
)

final_candidate_models.to_csv(
    FINAL_DIR / "final_candidate_models.csv",
    index=False
)

print("✓ final_candidate_models.csv")


# ------------------------------------------------------------
# 3. Excel workbook
# ------------------------------------------------------------

with pd.ExcelWriter(
    FINAL_DIR / "009_final_model_comparison.xlsx",
    engine="openpyxl"
) as writer:

    final_model_comparison.to_excel(
        writer,
        sheet_name="All Models",
        index=False
    )

    final_candidate_models.to_excel(
        writer,
        sheet_name="Final Candidates",
        index=False
    )

print("✓ 009_final_model_comparison.xlsx")


print("\n" + "=" * 70)
print("FINAL COMPARISON TABLES SAVED")
print("=" * 70)

print(f"Directory: {FINAL_DIR}")

======================================================================
SAVING FINAL COMPARISON TABLES
======================================================================
✓ final_model_comparison.csv
✓ final_candidate_models.csv
✓ 009_final_model_comparison.xlsx

======================================================================
FINAL COMPARISON TABLES SAVED
======================================================================
Directory: /content/drive/MyDrive/FitnessML_Master/results/009_final_results